services:
  db:
    image: docker.io/library/postgres:18.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-example}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-prs}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-prs}"]
      interval: 1s
      retries: 5
      timeout: 5s

  migrate:
    image: docker.io/migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER:-postgres}:${DB_PASSWORD:-example}@db:5432/${DB_NAME:-prs}?sslmode=disable",
        "up",
      ]

  restapi:
    build: .
    image: avito-pr:latest
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: ${DB_PASSWORD:-example}
      DB_USER: ${DB_USER:-postgres}
      DB_NAME: ${DB_NAME:-prs}
